ALTER TABLE [dbo].[tblCARD_FACE_SET] DROP CONSTRAINT [FK__tblCARD_F__CardF__05D8E0BE]
GO
ALTER TABLE [dbo].[tblCARD_FACE_SET_PLATFORM] DROP CONSTRAINT [FK__tblCARD_F__CardF__0C85DE4D]
GO

ALTER TABLE [dbo].[tblCARD_FACE_TYPE] DROP CONSTRAINT [FK__tblCARD_F__CardF__5CD6CB2B]
GO
ALTER TABLE [dbo].[tblCARD_FACE_SUPERTYPE] DROP CONSTRAINT [FK__tblCARD_F__CardF__59063A47]
GO
ALTER TABLE [dbo].[tblCARD_FACE_SUBTYPE] DROP CONSTRAINT [FK__tblCARD_F__CardF__60A75C0F]
GO
